name: Deploy Laravel Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'  # Ensure this matches your PHP version
          extensions: mbstring, bcmath
          coverage: none

      - name: Install Composer
        run: |
          curl -sS https://getcomposer.org/installer | php
          php composer.phar install 

      - name: Run Composer Update
        run: |
          php composer.phar update

      - name: Deploy Application
        run: |
          # Your deployment commands, e.g., Laravel Artisan commands, deployment steps
          php artisan migrate --force
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

